export const CHNAGE_ACTION_STATUS = 'CHNAGE_ACTION_STATUS';
export const TEST_REQUEST = 'TEST_REQUEST';
export const TEST_REQUEST_SUCCESS = 'TEST_REQUEST_SUCCESS';
export const TEST_REQUEST_FAILED = 'TEST_REQUEST_FAILED';
